### ISSUE TITLE
Hardcoded twitch rewards link 

### ISSUE THREAD

**Issue by HuthTV** [Koodattu/twitch-song-request-desktop#9]
The button opening channel point rewards page does not direct to users channel. It instead will try to open vaarattu twitch channel

![image](https://github.com/Koodattu/twitch-song-request-desktop/assets/85683980/aafcca2d-6aa5-41e9-98ce-a521d1033f54)

https://github.com/Koodattu/twitch-song-request-desktop/blob/75ec20fb8f02682dea336556f8053feaf070b88a/TwitchSongRequest/Styles/Resources.xaml#L21

**Comment by Koodattu** [comment]
Nice to see someone using the application though! I'll get this fixed as soon as I have the time. Thanks a lot for testing and I'll take all the feedback. You always try to think of everything, but developing something like this in a vacuum by yourself causes issues like this.
